---
title: "ANA 515 Assignment 1"
author: "Rashmitha Pasupureddy"
date: "2022-06-07"
output:
  html_document:
    theme:
      bootswatch: darkly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r gun_deaths, include=FALSE}
url <- "https://raw.githubusercontent.com/fivethirtyeight/guns-data/master/full_data.csv"
gun_deaths <- read.csv(url)
```

```{r youth, include=FALSE}
library(tidyverse)
library(knitr)
library(bslib)
youth <- filter (gun_deaths, age <=65)
summary (youth)
```

```{r, include=FALSE}
View(youth)
TotalDeaths <- nrow(gun_deaths)
SixtyFiveAndOlder <- nrow(gun_deaths)-(nrow(youth))
```

We have data of about `r TotalDeaths` individuals killed by guns. Only `r SixtyFiveAndOlder` are older than 65. The distribution of the remainder is shown below:

# Gun Deaths by Age
```{r youth-dist, echo = FALSE} 
youth %>% 
ggplot(aes(age)) + 
geom_freqpoly(binwidth = 1) 
```

# Gun deaths by Race 
```{r race-dist, echo = FALSE} 
youth %>% 
ggplot(aes(fct_infreq(race) %>% fct_rev())) + 
geom_bar() + coord_flip() + 
labs(x = "Victim race") 
```

